### PR TITLE
Add some tests

### PR DESCRIPTION
**Pull request by davidxia**

### CODE REVIEW

**Comment by davidxia** [comment]
@rohansingh It's a bit hard to write meaningful tests that aren't brittle because these classes are so tied to bouncy castle. Maybe we should just have some integration tests that check TLS handshakes work?

**Comment by nresare** [comment]
:+1: 

(As a very minor question of style, I'm unsure about whether it is a good idea to mock a ByteArrayOutputStream instead of just using a plain one and extract the byte array.)

**Comment by nresare** [comment]
@davidxia  now that we have a server implementation we can do a full stack test case :)

**Comment by davidxia** [comment]
Yea I'll try to come up with something for that.

On Monday, November 9, 2015, Noa Resare <notifications@github.com> wrote:

> @davidxia <https://github.com/davidxia> now that we have a server
> implementation we can do a full stack test case :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spotify/ssh-tls/pull/5#issuecomment-155094863>.
>


-- 
David Xia
Software Engineer
dxia@spotify.com

**Comment by davidxia** [comment]
@nresare Yea. I'll use a real OutputStream.

**Pull request merged**
